# Generated by Django 5.0.1 on 2024-01-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_project',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
